[package]
name = "blitz-net"
version = "0.1.0"
edition = "2021"

[dependencies]
blitz-traits = { path = "../blitz-traits" }
tokio = { workspace = true }
reqwest = { workspace = true }
data-url = { workspace = true }
thiserror = { workspace = true }
